# Generated by Django 5.2.16 on 2026-08-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day47app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='create_time',
            field=models.DateField(verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='dep',
            field=models.ForeignKey(default='选择部门', on_delete=django.db.models.deletion.CASCADE, to='day47app.department'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '女'), (1, '男')], default='选择性别', verbose_name='性别'),
        ),
    ]
