# Generated by Django 5.2.16 on 2026-08-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day47app', '0002_alter_userinfo_create_time_alter_userinfo_dep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.IntegerField(default=3000, verbose_name='价钱')),
                ('level', models.SmallIntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4')], default=1, verbose_name='等级')),
                ('status', models.SmallIntegerField(choices=[(0, 'not occupied'), (1, 'occupied')], default=0, verbose_name='状态')),
            ],
        ),
    ]
