# Generated by Django 5.2.16 on 2026-08-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day47app', '0003_prettynumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynumber',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='手机号'),
        ),
    ]
